name: CI for Next.js with Docker + Postgres

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Lancer Docker Compose (build + run)
      - name: Run Docker Compose
        run: |
          docker-compose -f ./jvthecode/docker-compose.yml up --build -d
          echo "Attente que Next.js démarre..."
          sleep 15  # ajuste si ton app prend plus de temps

      # 3️⃣ Vérifier que l'app Next.js répond
      - name: Check Next.js app is running
        run: |
          curl --fail http://localhost:3000 || (echo "App failed to start" && exit 1)

      # 4️⃣ Nettoyage : arrêter tous les conteneurs
      - name: Tear down
        if: always()
        run: docker-compose -f ./jvthecode/docker-compose.yml down
