name: CI for Next.js with Docker + Postgres

on:
pull_request:
branches:
  - main

jobs:
build-and-test:
runs-on: ubuntu-latest

steps:
  # 1️⃣ Récupérer le code
  - name: Checkout code
    uses: actions/checkout@v4

  # 2️⃣ Lancer Docker Compose (build + run)
  - name: Run Docker Compose
    run: |
      docker compose up --build -d
      echo "Attente que Next.js démarre..."
      sleep 15  # ajuste si ton app prend plus de temps

  # 3️⃣ Vérifier que l'app Next.js répond
  - name: Wait for Next.js
    run: |
      for i in {1..15}; do
        if curl --silent --fail <http://localhost:3000>; then
          echo "Next.js app is up!"
          exit 0
        fi
        echo "Waiting for Next.js to start... ($i/15)"
        sleep 5
      done
      echo "Next.js app failed to start after 75 seconds"
      exit 1

  # 4️⃣ Nettoyage : arrêter tous les conteneurs
  - name: Tear down
    if: always()
    run: docker-compose -f ./jvthecode/docker-compose.yml down
